src/Entity/Ingredient.php
<?php

namespace App\Entity;

use App\Repository\IngredientRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=IngredientRepository::class)
 */
class Ingredient
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;


    /**
     * @ORM\ManyToMany(targetEntity=Recipe::class, inversedBy="ingredients")
     */
    private $recipes;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getRecipes()
    {
        return $this->recipes;
    }

    /**
     * @param mixed $recipes
     * @return Ingredient
     */
    public function setRecipes($recipes)
    {
        $this->recipes = $recipes;
        return $this;
    }


}

templates/pages/all_recipes.html.twig
{% extends "base.html.twig" %}

{% block title %}Toutes les recettes{% endblock %}
{% block body %}

    <div class="container">
        <p class="important">
            Voici la liste de toutes les recettes
        </p>

    {% for pair in recipes |batch(2)%}
    <div class="row">

        {% for recipe in pair %}
            <div class="col">
                <div class="card mb-2" >
                    <img class="card-img-top" src="{{ recipe.imageurl }}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{{ recipe.title }}</h5>
                        <p class="card-text">{{ recipe.description }}</p>
                        <a href="{{ path('recipe.show', {id: recipe.id, slug: recipe.slug}) }}" class="btn btn-primary">Voir le détail</a>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>
    {% endfor %}

        <div class="navigation mb-5">
            {{ knp_pagination_render(recipes) }}
        </div>
    </div>
{% endblock %}

templates/pages/home.html.twig
{% extends "base.html.twig" %}

{% block title %}Accueil{% endblock %}
{% block head %}
    {{ parent() }}
{% endblock %}
{% block body %}
    <h1>Index</h1>
    <p class="important">
        Welcome on my awesome homepage.
    </p>
{% endblock %}

templates/pages/show.html.twig
{% extends "base.html.twig" %}

{% block title %}Toutes les recettes{% endblock %}
{% block head %}
    {{ parent() }}
{% endblock %}

{% block body %}
    <div class="container mt-4">
        <h1>{{ recipe.title }}</h1>
         <img src="{{ recipe.imageurl }}"/>
        <p>{{ recipe.description }}</p>
    </div>
{% endblock %}